name: holy_love
description: "A Christian dating app where hearts connect through faith"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^14.6.1
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # Forms & Validation
  formz: ^0.7.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Image handling
  image_picker: ^1.1.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Storage
  shared_preferences: ^2.3.3
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/ 