// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHS8o2IeqV_E11_KvqLb40eekuIHuExU',
    appId: '1:540961635657:web:2dc19eb09cc81423682e98',
    messagingSenderId: '540961635657',
    projectId: 'holy-love-2025-07-11',
    authDomain: 'holy-love-2025-07-11.firebaseapp.com',
    storageBucket: 'holy-love-2025-07-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47Lc1hvXuNDZcwCOUBHdPWX5mrRL5QaE',
    appId: '1:540961635657:android:1a3a1c1970ba34ff682e98',
    messagingSenderId: '540961635657',
    projectId: 'holy-love-2025-07-11',
    storageBucket: 'holy-love-2025-07-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfyC09juxsWfH7jymPQMV5Q77Wfy71DIk',
    appId: '1:540961635657:ios:2a30baeab7a8c44c682e98',
    messagingSenderId: '540961635657',
    projectId: 'holy-love-2025-07-11',
    storageBucket: 'holy-love-2025-07-11.firebasestorage.app',
    iosBundleId: 'com.holylove.app.holyLove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfyC09juxsWfH7jymPQMV5Q77Wfy71DIk',
    appId: '1:540961635657:ios:2a30baeab7a8c44c682e98',
    messagingSenderId: '540961635657',
    projectId: 'holy-love-2025-07-11',
    storageBucket: 'holy-love-2025-07-11.firebasestorage.app',
    iosBundleId: 'com.holylove.app.holyLove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHS8o2IeqV_E11_KvqLb40eekuIHuExU',
    appId: '1:540961635657:web:13837206a46c340c682e98',
    messagingSenderId: '540961635657',
    projectId: 'holy-love-2025-07-11',
    authDomain: 'holy-love-2025-07-11.firebaseapp.com',
    storageBucket: 'holy-love-2025-07-11.firebasestorage.app',
  );
}
